const coOrganizer = [
  {
    name: 'Dystopia Labs',
    logo: 'https://c.gitcoin.co/grants/ef48be2de9903230b8fc65d96b7d7652/dl_final_v1.0-01.jpg',
    link: 'https://dystopialabs.com/',
    repo: '',
  },
]

const Sponsors = [
  {
    name: 'Krypto Seoul',
    logo: 'https://media-exp1.licdn.com/dms/image/C510BAQFSFHVYpT4zkA/company-logo_200_200/0/1525685600987?e=1616630400&v=beta&t=S7edq0x5TT_puT1AOHkN9mysmNC-3llw2xvlq236vpE',
    link: 'https://www.linkedin.com/company/kryptoseoul/',
  },
  {
    name: 'Cosmos India',
    logo: 'https://cosmosindia.network/images/logo_white.png',
    link: 'https://cosmosindia.network/',
  },
  {
    name: 'nonce classic',
    logo: 'https://nonce.community/home',
    link: 'https://nonce.community/classic',
  },
  {
    name: 'DSRV',
    logo: 'https://v.fastcdn.co/u/049d6bf0/54247336-0-dsrv.png',
    link: '',
  },
  {
    name: 'Stanford journal of blockchain law & policy',
    logo: 'https://resize.pubpub.org/fit-in/0x200/skt57kwq/61531037600639.png',
    link: 'https://stanford-jblp.pubpub.org/',
  },
  {
    name: 'Cosmos',
    logo: 'https://v.fastcdn.co/u/049d6bf0/54652846-0-TPc0BKN--1.jpg',
    link: '',
  },
  {
    name: 'IRISnet',
    logo: 'https://www.irisnet.org/public/irisnet/presskit/IRISNet%20rebrand%20Horizontal-white.png',
    link: 'https://www.irisnet.org/',
  },
]

const Companies = [
  // {
  //   name: '',
  //   logo: '',
  //   link: '',
  //   repo: '',
  // },
  {
    name: 'Informal Systems',
    logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
    link: 'https://informal.systems/',
    repo: 'https://github.com/informalsystems',
  },
  {
    name: 'Interchain',
    logo: 'https://avatars0.githubusercontent.com/u/46904261?s=200&v=4',
    link: 'https://interchain.io/',
    repo: 'https://github.com/interchainio',
  },
  {
    name: 'Interchain Berlin',
    logo: 'https://avatars1.githubusercontent.com/u/61239025?s=200&v=4',
    link: 'https://interchain.berlin/',
    repo: 'https://github.com/interchainberlin',
  },
  {
    name: 'Tendermint',
    logo: 'https://avatars2.githubusercontent.com/u/7572940?s=200&v=4',
    link: 'https://tendermint.com/',
    repo: 'https://github.com/tendermint',
  },
  {
    name: 'iqlusion',
    logo: 'https://avatars1.githubusercontent.com/u/34927277?s=200&v=4',
    link: 'https://www.iqlusion.io/',
    repo: 'https://github.com/iqlusioninc',
  },
  {
    name: 'Paradigm',
    logo: 'https://twitter.com/paradigm/photo',
    link: 'https://www.paradigm.xyz/',
    repo: '',
  },
  {
    name: 'Sikka',
    logo: 'https://twitter.com/SikkaTech/photo',
    link: 'https://www.sikka.tech/',
    repo: '',
  },
  {
    name: 'Agoric',
    logo: 'https://avatars0.githubusercontent.com/u/26842028?s=200&v=4',
    link: 'https://agoric.com/',
    repo: 'https://github.com/Agoric',
  },
  {
    name: 'Confio',
    logo: 'https://avatars1.githubusercontent.com/u/34384539?s=200&v=4',
    link: 'https://confio.tech/',
    repo: 'https://github.com/confio',
  },
  {
    name: 'Althea',
    logo: 'https://avatars0.githubusercontent.com/u/25123050?s=200&v=4',
    link: 'https://althea.net/',
    repo: 'https://github.com/althea-net',
  },
  {
    name: 'Lazy Ledger',
    logo: 'https://avatars3.githubusercontent.com/u/54859940?s=200&v=4',
    link: 'https://lazyledger.org/',
    repo: 'https://github.com/lazyledger',
  },
  {
    name: 'Figment',
    logo: 'https://avatars0.githubusercontent.com/u/39868583?s=200&v=4',
    link: 'http://figment.io/',
    repo: 'https://github.com/figment-networks',
  },
  {
    name: 'Aave',
    logo: 'https://avatars3.githubusercontent.com/u/47617460?s=200&v=4',
    link: 'https://aave.com/',
    repo: 'https://github.com/aave',
  },
  {
    name: 'vulcarize',
    logo: 'https://v.fastcdn.co/u/049d6bf0/53725238-0-7U4eMQhT.jpg',
    link: '',
    repo: '',
  },
  {
    name: 'NYM',
    logo: 'https://avatars3.githubusercontent.com/u/51752891?s=200&v=4',
    link: 'https://nymtech.net/',
    repo: 'https://github.com/nymtech',
  },
  {
    name: 'THORChain',
    logo: 'https://avatars3.githubusercontent.com/u/40639099?s=200&v=4',
    link: 'https://thorchain.org/',
    repo: 'https://github.com/thorchain',
  },
  {
    name: 'IRIS Network',
    logo: 'https://avatars3.githubusercontent.com/u/33032395?s=200&v=4',
    link: 'https://www.irisnet.org/',
    repo: 'https://github.com/irisnet',
  },
  {
    name: 'Chorus',
    logo: 'https://avatars1.githubusercontent.com/u/36706567?s=200&v=4',
    link: 'https://www.chorus.one/',
    repo: 'https://github.com/ChorusOne',
  },
  {
    name: 'VEGA',
    logo: 'https://v.fastcdn.co/u/049d6bf0/54700306-0-Vega-whiteonblack.jpg',
    link: 'https://vega.xyz/background/',
    repo: '',
  },
  {
    name: 'Crypto',
    logo: 'https://pbs.twimg.com/profile_images/920233201301254144/oCw2s3GI_400x400.jpg',
    link: 'https://crypto.com/en/index.html',
    repo: '',
  },
  {
    name: 'Zcash',
    logo: 'https://avatars2.githubusercontent.com/u/16122764?s=200&v=4',
    link: 'https://z.cash/',
    repo: 'https://github.com/zcash',
  },
  {
    name: 'Terra',
    logo: 'https://avatars0.githubusercontent.com/u/38208150?s=200&v=4',
    link: 'https://terra.money/',
    repo: 'https://github.com/terra-project',
  },
  {
    name: 'Nomic',
    logo: 'https://avatars3.githubusercontent.com/u/44356692?s=200&v=4',
    link: 'https://nomic.io/',
    repo: 'https://github.com/nomic-io',
  },
  {
    name: 'Kava',
    logo: 'https://avatars1.githubusercontent.com/u/36107286?s=200&v=4',
    link: 'https://www.kava.io/',
    repo: 'https://github.com/Kava-Labs',
  },
  {
    name: 'WalletConnect',
    logo: 'https://avatars0.githubusercontent.com/u/37784886?s=200&v=4',
    link: 'https://walletconnect.org/',
    repo: 'https://github.com/WalletConnect',
  },
  {
    name: 'FOAM',
    logo: 'https://avatars0.githubusercontent.com/u/18058778?s=200&v=4',
    link: 'https://foam.space/',
    repo: 'https://github.com/f-o-a-m',
  },
  {
    name: 'ChainSafe',
    logo: 'https://avatars2.githubusercontent.com/u/27474093?s=200&v=4',
    link: 'https://chainsafe.io/',
    repo: 'https://github.com/ChainSafe',
  },
  {
    name: 'Persistence',
    logo: 'https://twitter.com/PersistenceOne/photo',
    link: 'https://persistence.one/',
    repo: '',
  },
  {
    name: 'Sifchain',
    logo: 'https://avatars2.githubusercontent.com/u/71144030?s=200&v=4',
    link: 'https://sifchain.finance/',
    repo: 'https://github.com/Sifchain',
  },
  {
    name: 'Starname',
    logo: 'https://avatars0.githubusercontent.com/u/34400253?s=200&v=4',
    link: 'https://starname.me/',
    repo: 'https://github.com/iov-one',
  },
  {
    name: 'Secret Foundation',
    logo: 'https://avatars3.githubusercontent.com/u/64166582?s=200&v=4',
    link: 'https://scrt.network/',
    repo: 'https://github.com/SecretFoundation',
  },
  {
    name: 'ixo',
    logo: 'https://avatars0.githubusercontent.com/u/31655095?s=200&v=4',
    link: 'https://ixo.world/',
    repo: 'https://github.com/ixofoundation',
  },
  {
    name: 'Regen Network',
    logo: 'https://avatars1.githubusercontent.com/u/32378558?s=200&v=4',
    link: 'https://www.regen.network/',
    repo: 'https://github.com/regen-network',
  },
  {
    name: 'Block Science',
    logo: 'https://twitter.com/block_science/photo',
    link: 'https://block.science/',
    repo: '',
  },
  {
    name: 'Forbole',
    logo: 'https://avatars3.githubusercontent.com/u/32561566?s=200&v=4',
    link: 'https://www.forbole.com/',
    repo: 'https://github.com/forbole',
  },
  {
    name: 'B-Harvest',
    logo: 'https://avatars3.githubusercontent.com/u/40380785?s=200&v=4',
    link: 'https://bharvest.io/',
    repo: 'https://github.com/b-harvest',
  },
  {
    name: 'Legendary Requirements',
    logo: 'http://legreq.com/images/logo.png',
    link: 'http://legreq.com/',
    repo: '',
  },
  {
    name: 'Cosmostation',
    logo: 'https://avatars2.githubusercontent.com/u/49175386?s=200&v=4',
    link: 'https://www.cosmostation.io/',
    repo: 'https://github.com/cosmostation',
  },
  {
    name: 'Stake Capital',
    logo: 'https://avatars3.githubusercontent.com/u/45174564?s=200&v=4',
    link: '',
    repo: 'https://github.com/stake-capital',
  },
  {
    name: 'Summa',
    logo: 'https://twitter.com/summa_one/photo',
    link: 'https://summa.one/',
    repo: '',
  },
]