export const Speakers = [
  // 52
  // {
  //   profile: '',
  //   name: '',
  //   title: '',
  //   social: '',
  //   company: {
  //     name: '',
  //     logo: '',
  //     link: '',
  //   },
  // },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C5603AQFbmFbR5-FmPg/profile-displayphoto-shrink_200_200/0/1517361673107?e=1614211200&v=beta&t=O8ciWwdNOyLP6ndh2edgsNV0JK2SxVq4tggpH0oc6gw',
    name: 'Ethan Buchman',
    title: 'Co-Founder of Cosmos',
    social: 'https://twitter.com/buchmanster',
    company: {
      name: 'Informal Systems',
      logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
      link: 'https://informal.systems/',
      repo: 'https://github.com/informalsystems',
    },
  },
  {
    profile: 'https://twitter.com/billyrennekamp/photo',
    name: 'Billy Rennekamp',
    title: 'Grants',
    social: 'https://twitter.com/billyrennekamp',
    company: {
      name: 'Interchain Berlin',
      logo: 'https://avatars1.githubusercontent.com/u/61239025?s=200&v=4',
      link: 'https://interchain.berlin/',
      repo: 'https://github.com/interchainberlin',
    },
  },
  {
    profile: 'https://twitter.com/zmanian/photo',
    name: 'Zaki Manian',
    title: 'Co-Founder',
    social: 'https://twitter.com/zmanian',
    company: {
      name: 'iqlusion',
      logo: 'https://avatars1.githubusercontent.com/u/34927277?s=200&v=4',
      link: 'https://www.iqlusion.io/',
      repo: 'https://github.com/iqlusioninc',
    },
  },
  {
    profile: 'https://twitter.com/_charlienoyes/photo',
    name: 'Charlie Noyes',
    title: 'Partner',
    social: 'https://twitter.com/_charlienoyes',
    company: {
      name: 'Paradigm',
      logo: 'https://twitter.com/paradigm/photo',
      link: 'https://www.paradigm.xyz/',
      repo: '',
    },
  },
  {
    profile: 'https://twitter.com/sunnya97/photo',
    name: 'Sunny Aggarwal',
    title: 'Researcher',
    social: 'https://twitter.com/sunnya97',
    company: {
      name: 'Sikka',
      logo: 'https://twitter.com/SikkaTech/photo',
      link: 'https://www.sikka.tech/',
      repo: '',
    },
  },
  {
    profile: 'https://twitter.com/_tessr/photo',
    name: 'Tess Rinearson',
    title: 'VP of Engineering',
    social: 'https://twitter.com/_tessr',
    company: {
      name: 'Interchain Berlin',
      logo: 'https://avatars1.githubusercontent.com/u/61239025?s=200&v=4',
      link: 'https://interchain.berlin/',
      repo: 'https://github.com/interchainberlin',
    },
  },
  {
    profile: 'https://twitter.com/DeanTribble',
    name: 'Dean Tribble',
    title: 'CEO',
    social: 'https://twitter.com/DeanTribble/photo',
    company: {
      name: 'Agoric',
      logo: 'https://avatars0.githubusercontent.com/u/26842028?s=200&v=4',
      link: 'https://agoric.com/',
      repo: 'https://github.com/Agoric',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4D03AQF7RNCPbZm8mQ/profile-displayphoto-shrink_200_200/0/1582625173127?e=1614211200&v=beta&t=JITW2FtUVEj4BFaS55P6noGUF7_BjB8fggFgMSyvVq4',
    name: 'Zarko Milosevic',
    title: 'Chief Scientist',
    social: 'https://www.linkedin.com/in/zarko-milosevic-8a87375/',
    company: {
      name: 'Informal Systems',
      logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
      link: 'https://informal.systems/',
      repo: 'https://github.com/informalsystems',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQF4ZGmdIRTw5w/profile-displayphoto-shrink_200_200/0/1578128089532?e=1614211200&v=beta&t=1Q5L-Cb8hVTcEqS1gaxkXvDngHtZD1nYbqpnBUE3T4s',
    name: 'Martin Worner',
    title: 'COO & VP of Product',
    social: 'https://www.linkedin.com/in/martinworner/',
    company: {
      name: 'Confio',
      logo: 'https://avatars1.githubusercontent.com/u/34384539?s=200&v=4',
      link: 'https://confio.tech/',
      repo: 'https://github.com/confio',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C5603AQHKxgaBAIH8DA/profile-displayphoto-shrink_200_200/0/1557881594406?e=1614211200&v=beta&t=WCc5qhbtg5qkdvYP2HNH4FnyzLEGgK1LslkLt9dY2DM',
    name: 'Deborah Simpier',
    title: 'Co-Founder',
    social: 'https://twitter.com/DeborahSimpier',
    company: {
      name: 'Althea',
      logo: 'https://avatars0.githubusercontent.com/u/25123050?s=200&v=4',
      link: 'https://althea.net/',
      repo: 'https://github.com/althea-net',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4D03AQEyFt9KJTuzTQ/profile-displayphoto-shrink_200_200/0/1597325878777?e=1614211200&v=beta&t=slhgREPXlr2nJkXcohjFUn0c2gNqQKnyHff7BiU1NYI',
    name: 'Mustafa Al-Bassam',
    title: 'CEO & Co-Founder',
    social: 'https://twitter.com/musalbas',
    company: {
      name: 'Lazy Ledger',
      logo: 'https://avatars3.githubusercontent.com/u/54859940?s=200&v=4',
      link: 'https://lazyledger.org/',
      repo: 'https://github.com/lazyledger',
    },
  },
  {
    profile: 'https://twitter.com/futurechimp/photo',
    name: 'Dave Hrycyszyn',
    title: 'CTO & Co-Founder',
    social: 'https://twitter.com/futurechimp',
    company: {
      name: 'NYM',
      logo: 'https://avatars3.githubusercontent.com/u/51752891?s=200&v=4',
      link: 'https://nymtech.net/',
      repo: 'https://github.com/nymtech',
    },
  },
  {
    profile: 'https://twitter.com/AFDudley0/photo',
    name: 'Rick Dudley',
    title: 'CEO & Founder',
    social: 'https://twitter.com/afdudley0?lang=en',
    company: {
      name: 'vulcarize',
      logo: 'https://v.fastcdn.co/u/049d6bf0/53725238-0-7U4eMQhT.jpg',
      link: '',
      repo: '',
    },
  },
  {
    profile: 'https://twitter.com/zcpeng/photo',
    name: 'Peng Zhong',
    title: 'CEO',
    social: 'https://twitter.com/zcpeng',
    company: {
      name: 'Tendermint',
      logo: 'https://avatars2.githubusercontent.com/u/7572940?s=200&v=4',
      link: 'https://tendermint.com/',
      repo: 'https://github.com/tendermint',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQGSQzio-2-ncA/profile-displayphoto-shrink_200_200/0/1590955123411?e=1614211200&v=beta&t=SMUVmtyGJcNF4ExFyP-13W0KEWzjbBAekY7SA7un6UM',
    name: 'Stani Kulechov',
    title: 'CEO & Founder',
    social: 'https://www.linkedin.com/in/stani-kulechov-361284132/',
    company: {
      name: 'Aave',
      logo: 'https://avatars3.githubusercontent.com/u/47617460?s=200&v=4',
      link: 'https://aave.com/',
      repo: 'https://github.com/aave',
    },
  },
  {
    profile: 'https://twitter.com/Ether_Gavin/photo',
    name: 'Gavin Birch',
    title: 'Protocol Analyst',
    social: 'https://twitter.com/ether_gavin?lang=en',
    company: {
      name: 'Figment',
      logo: 'https://avatars0.githubusercontent.com/u/39868583?s=200&v=4',
      link: 'http://figment.io/',
      repo: 'https://github.com/figment-networks',
    },
  },
  {
    profile: 'https://twitter.com/jpthorbjornsen/photo',
    name: 'JP Thorbjornsen',
    title: 'Contributor',
    social: 'https://twitter.com/jpthorbjornsen',
    company: {
      name: 'THORChain',
      logo: 'https://avatars3.githubusercontent.com/u/40639099?s=200&v=4',
      link: 'https://thorchain.org/',
      repo: 'https://github.com/thorchain',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQEAb0WwzvuYhg/profile-displayphoto-shrink_200_200/0/1552578313610?e=1614211200&v=beta&t=Fp9SG0ex_kc5yTIq8PfxTb2yt4UbhSXzDPte6zyrFMY',
    name: 'Igor Konnov',
    title: 'Principal Research Scientist',
    social: 'https://www.linkedin.com/in/igor-konnov-7683241/',
    company: {
      name: 'Informal Systems',
      logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
      link: 'https://informal.systems/',
      repo: 'https://github.com/informalsystems',
    },
  },
  {
    profile: 'https://twitter.com/dogemos/photo',
    name: 'Josh Lee',
    title: 'Ecosystem Analyst',
    social: 'https://twitter.com/dogemos',
    company: {
      name: 'Tendermint',
      logo: 'https://avatars2.githubusercontent.com/u/7572940?s=200&v=4',
      link: 'https://tendermint.com/',
      repo: 'https://github.com/tendermint',
    },
  },
  {
    profile: 'https://twitter.com/hu_zhiwei/photo',
    name: 'Jeffrey Hu',
    title: 'Research Director',
    social: 'https://twitter.com/hu_zhiwei',
    company: {
      name: 'IRIS Network',
      logo: 'https://avatars3.githubusercontent.com/u/33032395?s=200&v=4',
      link: 'https://www.irisnet.org/',
      repo: 'https://github.com/irisnet',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQEwIFMdPQR6kA/profile-displayphoto-shrink_200_200/0/1517538452107?e=1614211200&v=beta&t=6-ecJ7AI2qfpYe5Ik5aK1Ui7REw2ddZD2XJ93w4VguE',
    name: 'Felix Lutsch',
    title: 'Business Development',
    social: 'https://twitter.com/FelixLts',
    company: {
      name: 'Chorus',
      logo: 'https://avatars1.githubusercontent.com/u/36706567?s=200&v=4',
      link: 'https://www.chorus.one/',
      repo: 'https://github.com/ChorusOne',
    },
  },
  {
    profile: 'https://twitter.com/KursaweKlaus/photo',
    name: 'Klaus Kursawe',
    title: 'Consensus Researche',
    social: 'https://twitter.com/KursaweKlaus',
    company: {
      name: 'VEGA',
      logo: 'https://v.fastcdn.co/u/049d6bf0/54700306-0-Vega-whiteonblack.jpg',
      link: 'https://vega.xyz/background/',
      repo: '',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4D03AQE3Wt7I35DHZA/profile-displayphoto-shrink_200_200/0/1516895244957?e=1614211200&v=beta&t=R_x8ellXNFiAtIMDero1qwxkeaGKbxoDTF0yVwIzHYE',
    name: 'Tomas Tauber',
    title: 'Lead Engineer & Researcher',
    social: 'https://www.linkedin.com/in/tomtau/',
    company: {
      name: 'Crypto',
      logo: 'https://pbs.twimg.com/profile_images/920233201301254144/oCw2s3GI_400x400.jpg',
      link: 'https://crypto.com/en/index.html',
      repo: '',
    },
  },
  {
    profile: 'https://avatars1.githubusercontent.com/u/44879?s=460&v=4',
    name: 'Henry de Valence',
    title: 'Cryptographer',
    social: 'https://github.com/hdevalence',
    company: {
      name: 'Zcash',
      logo: 'https://avatars2.githubusercontent.com/u/16122764?s=200&v=4',
      link: 'https://z.cash/',
      repo: 'https://github.com/zcash',
    },
  },
  {
    profile: 'https://twitter.com/JoeAndrieu/photo',
    name: 'Joe Andrieu',
    title: 'President',
    social: 'https://twitter.com/JoeAndrieu',
    company: {
      name: 'Legendary Requirements',
      logo: 'http://legreq.com/images/logo.png',
      link: 'http://legreq.com/',
      repo: '',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C5603AQEtQOpySXV92w/profile-displayphoto-shrink_200_200/0/1593078713585?e=1614211200&v=beta&t=1m4yFBYv79WHdmKoDG4Q1INKAoNi_58q4KeHWwK680o',
    name: 'David Park',
    title: 'CMO',
    social: 'https://www.linkedin.com/in/davidparkcw/',
    company: {
      name: 'Cosmostation',
      logo: 'https://avatars2.githubusercontent.com/u/49175386?s=200&v=4',
      link: 'https://www.cosmostation.io/',
      repo: 'https://github.com/cosmostation',
    },
  },
  {
    profile: 'https://twitter.com/brapse/photo',
    name: 'Sean Braithwaite',
    title: 'CTO',
    social: 'https://twitter.com/brapse',
    company: {
      name: 'Informal Systems',
      logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
      link: 'https://informal.systems/',
      repo: 'https://github.com/informalsystems',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQHseLP49pKKlg/profile-displayphoto-shrink_200_200/0/1516949133784?e=1614211200&v=beta&t=uHJjwsdtVL60fzJmPA5vR2l-bMW4w2G5somsb2Jybl4',
    name: 'Arianne Flemming',
    title: 'COO',
    social: 'https://twitter.com/ArianneFlemming',
    company: {
      name: 'Informal Systems',
      logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
      link: 'https://informal.systems/',
      repo: 'https://github.com/informalsystems',
    },
  },
  {
    profile: 'https://twitter.com/d0h0k1/photo',
    name: 'Do Kwon',
    title: 'CEO & Founder',
    social: 'https://twitter.com/d0h0k1',
    company: {
      name: 'Terra',
      logo: 'https://avatars0.githubusercontent.com/u/38208150?s=200&v=4',
      link: 'https://terra.money/',
      repo: 'https://github.com/terra-project',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4D03AQGxuNeWQ0ZiMA/profile-displayphoto-shrink_200_200/0/1560970017523?e=1614211200&v=beta&t=0MQK0kk_k9JjqywyTf03KjxLG5FQyqtTWn23zRPvFfY',
    name: 'Julien Bouteloup',
    title: 'CEO & Founder',
    social: 'https://www.linkedin.com/in/jbouteloup/',
    company: {
      name: 'Stake Capital',
      logo: 'https://avatars3.githubusercontent.com/u/45174564?s=200&v=4',
      link: '',
      repo: 'https://github.com/stake-capital',
    },
  },
  {
    profile: 'https://pbs.twimg.com/media/D7llAQ_W4Acctd5?format=jpg&name=large',
    name: 'Brent Xu',
    title: 'Head of Strategy & Partnerships',
    social: '',
    company: {
      name: 'Tendermint',
      logo: 'https://avatars2.githubusercontent.com/u/7572940?s=200&v=4',
      link: 'https://tendermint.com/',
      repo: 'https://github.com/tendermint',
    },
  },
  {
    profile: 'https://twitter.com/_prestwich/photo',
    name: 'James Prestwich',
    title: 'Co-Founder',
    social: 'https://twitter.com/_prestwich',
    company: {
      name: 'Summa',
      logo: 'https://twitter.com/summa_one/photo',
      link: 'https://summa.one/',
      repo: '',
    },
  },
  {
    profile: 'https://twitter.com/juddkeppel/photo',
    name: 'Judd Keppel',
    title: 'Co-Founder',
    social: 'https://twitter.com/juddkeppel',
    company: {
      name: 'Nomic',
      logo: 'https://avatars3.githubusercontent.com/u/44356692?s=200&v=4',
      link: 'https://nomic.io/',
      repo: 'https://github.com/nomic-io',
    },
  },
  {
    profile: 'https://twitter.com/shaunbconway/photo',
    name: 'Dr. Shaun Conway',
    title: 'Founder',
    social: 'https://twitter.com/shaunbconway',
    company: {
      name: 'ixo',
      logo: 'https://avatars0.githubusercontent.com/u/31655095?s=200&v=4',
      link: 'https://ixo.world/',
      repo: 'https://github.com/ixofoundation',
    },
  },
  {
    profile: 'https://twitter.com/aaroncraelius/photo',
    name: 'Aaron Craelius',
    title: 'CTO',
    social: 'https://twitter.com/aaroncraelius',
    company: {
      name: 'Regen Network',
      logo: 'https://avatars1.githubusercontent.com/u/32378558?s=200&v=4',
      link: 'https://www.regen.network/',
      repo: 'https://github.com/regen-network',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQFKF8MqJwxrGg/profile-displayphoto-shrink_200_200/0/1516857568650?e=1614211200&v=beta&t=0qQX68y_dUROy26eDxWlSPy4G4krmZFN-OVbr7md6qM',
    name: 'Shruti Appiah',
    title: 'Research Scientist',
    social: 'https://www.linkedin.com/in/shrutiappiah/',
    company: {
      name: 'Block Science',
      logo: 'https://twitter.com/block_science/photo',
      link: 'https://block.science/',
      repo: '',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQEge1Fn49tp1A/profile-displayphoto-shrink_200_200/0/1517882116943?e=1614211200&v=beta&t=LAVAftf-HSOIx42XvQeBVSmYMfeLqrSLBnEDOpO2br4',
    name: 'Dev Ojha',
    title: 'Co-Founder',
    social: 'https://www.linkedin.com/in/dev-ojha-0/',
    company: {
      name: 'Sikka',
      logo: 'https://twitter.com/SikkaTech/photo',
      link: 'https://www.sikka.tech/',
      repo: '',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C5103AQHT81D919Rw7A/profile-displayphoto-shrink_200_200/0/1575389166767?e=1614211200&v=beta&t=_LKxsz3MyCBzn8C1sg_CBdxWj-cxJ_eLl8b4IBskiY0',
    name: 'Kwun Yeung',
    title: 'Co-Founder',
    social: 'https://www.linkedin.com/in/kwunyeung/',
    company: {
      name: 'Forbole',
      logo: 'https://avatars3.githubusercontent.com/u/32561566?s=200&v=4',
      link: 'https://www.forbole.com/',
      repo: 'https://github.com/forbole',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4E03AQFb4Lqdakq9aw/profile-displayphoto-shrink_200_200/0/1561537049421?e=1614211200&v=beta&t=KtDViWcDpLaFM4ML0LIjbI4E7gc624O7TOQZR6h8LCg',
    name: 'Hyung Yeon Lee',
    title: 'CEO',
    social: 'https://www.linkedin.com/in/hyung-yeon-lee-9113764a/',
    company: {
      name: 'B-Harvest',
      logo: 'https://avatars3.githubusercontent.com/u/40380785?s=200&v=4',
      link: 'https://bharvest.io/',
      repo: 'https://github.com/b-harvest',
    },
  },
  {
    profile: 'https://avatars2.githubusercontent.com/u/4323424?s=460&u=bb1ea38421038ad1a955e3d308c5361eeebee1bc&v=4',
    name: 'Joe Bowman',
    title: 'Platform & Software Engineering',
    social: 'https://github.com/joe-bowman',
    company: {
      name: 'Chorus',
      logo: 'https://avatars1.githubusercontent.com/u/36706567?s=200&v=4',
      link: 'https://www.chorus.one/',
      repo: 'https://github.com/ChorusOne',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C5603AQEdpVksj5iyvA/profile-displayphoto-shrink_200_200/0/1540835268272?e=1614211200&v=beta&t=eiQu3TGi2-TnO1X7mV82rvvUbscOBWAMHXQUqn_cslI',
    name: 'Jazear Brooks',
    title: 'Founder',
    social: 'https://www.linkedin.com/in/jazearbrooks/',
    company: {
      name: 'Sifchain',
      logo: 'https://avatars2.githubusercontent.com/u/71144030?s=200&v=4',
      link: 'https://sifchain.finance/',
      repo: 'https://github.com/Sifchain',
    },
  },
  {
    profile: 'https://twitter.com/deepanshutr/photo',
    name: 'Deepanshu Tripathi',
    title: 'CTO',
    social: 'https://twitter.com/deepanshutr',
    company: {
      name: 'Persistence',
      logo: 'https://twitter.com/PersistenceOne/photo',
      link: 'https://persistence.one/',
      repo: '',
    },
  },
  {
    profile: 'https://twitter.com/fekunze/photo',
    name: 'Federico Kunze Küllmer',
    title: 'Software Engineer',
    social: 'https://twitter.com/fekunze',
    company: {
      name: 'ChainSafe',
      logo: 'https://avatars2.githubusercontent.com/u/27474093?s=200&v=4',
      link: 'https://chainsafe.io/',
      repo: 'https://github.com/ChainSafe',
    },
  },
  {
    profile: 'https://twitter.com/frothcity/photo',
    name: 'Ryan John King',
    title: 'Co-Founder',
    social: 'https://twitter.com/frothcity',
    company: {
      name: 'FOAM',
      logo: 'https://avatars0.githubusercontent.com/u/18058778?s=200&v=4',
      link: 'https://foam.space/',
      repo: 'https://github.com/f-o-a-m',
    },
  },
  {
    profile: 'https://avatars1.githubusercontent.com/u/398285?s=460&u=d74f71fa075a95e0e85df4594b82fb429f79a760&v=4',
    name: 'Matt Bell',
    title: 'Co-Founder',
    social: 'https://github.com/mappum',
    company: {
      name: 'Nomic',
      logo: 'https://avatars3.githubusercontent.com/u/44356692?s=200&v=4',
      link: 'https://nomic.io/',
      repo: 'https://github.com/nomic-io',
    },
  },
  {
    profile: 'https://avatars2.githubusercontent.com/u/10136079?s=460&u=745a6a70fad54d544af5c22bac683612aadfcba6&v=4',
    name: 'Pedro Gomes',
    title: 'Founder',
    social: 'https://github.com/pedrouid',
    company: {
      name: 'WalletConnect',
      logo: 'https://avatars0.githubusercontent.com/u/37784886?s=200&v=4',
      link: 'https://walletconnect.org/',
      repo: 'https://github.com/WalletConnect',
    },
  },
  {
    profile: 'https://twitter.com/Scott_Stuart_/photo',
    name: 'Scott Stuart',
    title: 'Product',
    social: 'https://twitter.com/Scott_Stuart_',
    company: {
      name: 'Kava',
      logo: 'https://avatars1.githubusercontent.com/u/36107286?s=200&v=4',
      link: 'https://www.kava.io/',
      repo: 'https://github.com/Kava-Labs',
    },
  },
  {
    profile: 'https://avatars2.githubusercontent.com/u/8525850?s=460&u=9bfaf3fe79cb36263fcf65705c0f70654dc0a9cf&v=4',
    name: 'Chjango Unchained',
    title: 'Ecosystem Developer',
    social: 'https://github.com/Chjango',
    company: {
      name: 'Tendermint',
      logo: 'https://avatars2.githubusercontent.com/u/7572940?s=200&v=4',
      link: 'https://tendermint.com/',
      repo: 'https://github.com/tendermint',
    },
  },
  {
    profile: 'https://twitter.com/antoineherzog/photo',
    name: 'Antoine Herzog',
    title: 'CEO',
    social: 'https://twitter.com/antoineherzog',
    company: {
      name: 'Starname',
      logo: 'https://avatars0.githubusercontent.com/u/34400253?s=200&v=4',
      link: 'https://starname.me/',
      repo: 'https://github.com/iov-one',
    },
  },
  {
    profile: 'https://media-exp1.licdn.com/dms/image/C4D03AQGPNhVfX79Reg/profile-displayphoto-shrink_200_200/0/1517467825561?e=1614211200&v=beta&t=GNch28AXYYX_uZ_JyIkNZiHo0iim6bZWzCNbGWS8_qA',
    name: 'Guy Zyskind',
    title: 'Enigma\'s CEO speaking on behalf of the Secret Network',
    social: 'https://twitter.com/GuyZys',
    company: {
      name: 'Secret Foundation',
      logo: 'https://avatars3.githubusercontent.com/u/64166582?s=200&v=4',
      link: 'https://scrt.network/',
      repo: 'https://github.com/SecretFoundation',
    },
  },
  {
    profile: 'https://twitter.com/cwgoes/photo',
    name: 'Chris Goes',
    title: 'IBC Lead Dev',
    social: 'https://twitter.com/cwgoes',
    company: {
      name: 'Interchain Berlin',
      logo: 'https://avatars1.githubusercontent.com/u/61239025?s=200&v=4',
      link: 'https://interchain.berlin/',
      repo: 'https://github.com/interchainberlin',
    },
  },
  {
    profile: 'https://avatars1.githubusercontent.com/u/59489470?s=460&u=bd730522c9270f7276980d3c86a77da2b7d86dd2&v=4',
    name: 'Andrey Kuprianov',
    title: 'Senior Research Engineer',
    social: 'https://github.com/andrey-kuprianov',
    company: {
      name: 'Informal Systems',
      logo: 'https://avatars2.githubusercontent.com/u/59101308?s=200&v=4',
      link: 'https://informal.systems/',
      repo: 'https://github.com/informalsystems',
    },
  },
]